# Start from official Python base image
FROM python:3.11-slim

# set the working directory in the container
WORKDIR /app

# copy the local code to the container
COPY app.py .

# Set the default command
CMD ["python", "app.py"]